name: Auto-refresh of the apt repository

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PTA }}
  
      - name: Install dependencies
        run: sudo apt install gnupg

      - name: Load the private key from the secrets
        run: gpg --import <(base64 -d < <(printf "$KEY"))
        shell: bash
        env:
          KEY: ${{secrets.PRIVATE_KEY}}
          
      - name: Create the Packages file
        run: |
          cd ./apt
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          
      - name: Create the Release, Release.gpg and InRelease files
        run: |
          cd ./apt
          apt-ftparchive release . > Release
          gpg --default-key bennet.ranft@outlook.de -abs -o - Release > Release.gpg
          gpg --default-key bennet.ranft@outlook.de --clearsign -o - Release > InRelease
          
      - name: Commit the updated repository to github
        uses: EndBug/add-and-commit@v9.0.0
        with:
          default_author: github_actions
          message: Auto-refresh of the apt repository
